name: pull-request
on: [pull_request]

jobs:
  build:
    env:
      NEXT_PUBLIC_BASE_PATH: /airmap
    runs-on: ubuntu-latest
    steps:
      - name: checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v1.4.4
        with:
          node-version: 20.15.0
          registry-url: "https://registry.npmjs.org"
      - name: Install pnpm
        run: npm install -g pnpm@9
      - name: Install and Test
        run: |
          pnpm install
          pnpm format --check
          pnpm test
          pnpm build
